services:
  locations:
    build: .
#    env_file:
#      - .env
    ports:
      - "9092:9092"
    volumes:
      - /opt/home-planner/planner.db:/app/planner.db
      - /opt/home-planner/uploads:/app/static/uploads
    restart: unless-stopped